version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ipnetwork
    versions:
    - ">= 0.16.a, < 0.17"
  - dependency-name: id3
    versions:
    - 0.6.0
    - 0.6.1
    - 0.6.2
    - 0.6.3
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.1.1
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: pretty_assertions
    versions:
    - 0.7.1
  - dependency-name: nom
    versions:
    - 6.1.0
  - dependency-name: ipnetwork
    versions:
    - 0.17.0
